apiVersion: v1
kind: Service
metadata:
  name: myapp01-lb-with-metallb-annotation
  annotations:
    metallb.universe.tf/loadBalancerIPs: 172.18.10.85
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: myapp01-lb
  type: LoadBalancer
