apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp01-lb
  name: myapp01-lb
spec:
  ports:
  - name: portdetails
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp-01
  type: LoadBalancer
  loadBalancerIP: 172.18.10.20

