---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-01
  namespace: metallb-system
spec:
  addresses:
    - 172.18.20.20-172.18.20.30
  serviceAllocation:
    priority: 50

---

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool-02
  namespace: metallb-system
spec:
  addresses:
    - 172.18.20.40-172.18.20.50
  serviceAllocation:
    priority: 70
