apiVersion: v1
kind: Service
metadata:
  name: nginx-web
  annotations: 
    metallb.universe.tf/address-pool: pool-02
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nginx-web
    type: LoadBalancer
